#
# Continuous Integration workflow.
#
name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  #
  # Run every Saturday whether there have been changes or not.
  # Hopefully this will keep us in sync with upstream changes.
  #
  schedule:
    - cron: '17 8 * * SAT'
  #
  # Allow manual invocation, for example for feature branches.
  #
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Setup Java JDK
      uses: actions/setup-java@v3.13.0
      with:
        java-version: 17
        distribution: corretto

    - name: Set up Maven
      uses: s4u/maven-settings-action@v2.8.0
      with:
        servers: |
          [{
              "id": "ukf-packages",
              "username": "${{ github.actor }}",
              "password": "${{ secrets.GITHUB_TOKEN }}"
          }]

    - uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Which Maven?
      run: mvn -v

    - name: Build and test
      run: mvn --batch-mode --update-snapshots clean verify
